### ISSUE TITLE
can't find .rhl file

### ISSUE THREAD

**Issue by h-OUS-e** [lelandjobson/RhinoToEnergy2D#1]
Hello,

Thank you for releasing this awesome plugin. Unfortunately, I can't find the .rhl file in the repo, and the link provided in the slides is broken. Was there any update on that?

Thank you!

**Comment by lelandjobson** [comment]
Hello, I will take a look in a few

**Comment by h-OUS-e** [comment]
thanks!

**Comment by lelandjobson** [comment]
Ous,

Thank you for your patience: I have updated the link, here is the direct:

https://github.com/lelandjobson/RhinoToEnergy2D/releases/tag/1.0

You can grab the RHP from there.

Instructions are the same.

Note - bezier spline support still sucks (energy2d splines are weird) 0: so
change your curve degree / use polylines (:

Good luck!

Leland Jobson | lelandjobson.com
